# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 814)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(940, 450, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("position: absolute;\n"
"width: 110px;\n"
"height: 70px;\n"
"left: 952px;\n"
"top: 509px;\n"
"\n"
"background: #F0F0F0;\n"
"/* 1 */\n"
"\n"
"border-radius: 15px;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 1121, 761))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 260, 491, 131))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:#3E3562;")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 80, 531, 81))
        self.label_3.setStyleSheet("position: absolute;\n"
"width: 560px;\n"
"height: 78px;\n"
"left: 499px;\n"
"top: 175px;\n"
"\n"
"font-family: Montserrat Alternates;\n"
"font-style: normal;\n"
"font-weight: bold;\n"
"font-size: 64px;\n"
"line-height: 78px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #202543;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(284, 0, 821, 741))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(980, 450, 51, 61))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pandemic travel"))
        self.label.setText(_translate("MainWindow", "Так как границы  закрыты, это не \n"
"повод грустить. Внутренний туризм \n"
"никто не отменял!\n"
"Мы для вас собрали топ самых красивых \n"
"мест нашего Казахстана"))
        self.label_3.setText(_translate("MainWindow", "Pandemic travel"))
